### ISSUE TITLE
[ Unknown command:"ENDSTOP_PHASE_CALIBRATE"] 

### ISSUE THREAD

**Issue by Ejay-3D** [Guilouz/KlipperScreen-Flsun-V400#1]
**Describe the bug**
After Running 
ENDSTOPS_CALIBRATION macro error message on  ENDSTOP_PHASE_CALIBRATE command 

**To Reproduce**
1. Run ENDSTOPS_CALIBRATION macro 
2. See error

**Expected behavior**
ENDSTOP_PHASE_CALIBRATE command  should run ok 

**Screenshots**
in attachement 
![Capture d’écran 2022-10-13 à 13 36 15](https://user-images.githubusercontent.com/38557267/195586227-b0df395a-afde-4714-aab4-58d37de20d2a.png)

**Logfile**
attached 
[macros.txt](https://github.com/Guilouz/KlipperScreen-Flsun-V400/files/9776165/macros.txt)
[printer (3).txt](https://github.com/Guilouz/KlipperScreen-Flsun-V400/files/9776166/printer.3.txt)

[klippy (1).log](https://github.com/Guilouz/KlipperScreen-Flsun-V400/files/9776161/klippy.1.log)

Stock firmware , Screen updated from your Git.

**Comment by Ejay-3D** [comment]
Hello, I did the change in config.cfg but the issue remain . All the macros were already in macros.cfg . 
Any other hints ? 
Thanks 
[printer2.txt](https://github.com/Guilouz/KlipperScreen-Flsun-V400/files/9780184/printer2.txt)

**Comment by Guilouz** [comment]
ENDSTOP_PHASE_CALIBRATE is correct, see documentation here : https://www.klipper3d.org/Endstop_Phase.html

[endstop_phase stepper_a]
endstop_align_zero: false

[endstop_phase stepper_b]
endstop_align_zero: false

[endstop_phase stepper_c]
endstop_align_zero: false 

Are missing in your printer.cfg file.
